
services:

  source-database:
    container_name: source-database
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./sample_data/01_Chinook_PostgreSql.sql:/docker-entrypoint-initdb.d/01_Chinook_PostgreSql.sql
      - ./sample_data/02_multiple_users.sql:/docker-entrypoint-initdb.d/02_multiple_users.sql
      - ./.source-database-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d chinook -h localhost -p 5432" ]

  veilstream-postgres-proxy:
    container_name: veilstream-postgres-proxy
    image: veilstream/veilstream-postgres-proxy:latest
    env_file: ./.env
    environment:
      DATABASE_URI: postgresql://user:password@source-database:5432/chinook
    ports:
      - "5432:5432"
    depends_on:
      source-database:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail http://localhost/healthz/ready || exit 1"]
      interval: 10s
      retries: 6
      timeout: 5s
    logging:
      options:
        max-size: "10m"
        max-file: "3"
